version: '3.8'

services:
  # --- DATABASE (MariaDB) ---
  db:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_DATABASE: wordpress

  # --- PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma_container
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  # --- WORDPRESS ---
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wp_container
    restart: always
    volumes:
      - ./wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
    ports:
      - "8000:80"